name: Build & Push Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/francommit/go_learning/hello_world

    - name: Login
      run: echo "${{ github.token }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin

    - name: Push
      run: docker push docker.pkg.github.com/francommit/go_learning/hello_world:latest