name: Build Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build & Push image
      run: docker build . --file Dockerfile --tag 
      run: |
        echo "${{ github.token }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
        docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY}/go_learning/my-image-name:$(date +%s) .
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/go_learning/my-image-name:$(date +%s)